### PR TITLE
fix(pay-slip)[backend]: delete file from storage on record deletion

### LINKED ISSUE #31: fix(pay-slip): delete file from storage when a pay slip is deleted
## Summary

The `DELETE /api/pay-slips/{id}` endpoint only removes the database record. The actual file in GCS is never deleted, leaving orphaned objects in storage indefinitely.

## Problem

```
DELETE /api/pay-slips/{id}
  → deletes DB record ✓
  → file remains in GCS ✗
```

Over time this leads to unbounded storage growth with no way to identify or clean up the orphaned files, since the DB record (which holds the file path) is already gone.

## Fix

- Add a `DeleteFile(ctx, path string) error` method to the storage layer
- In the `DeletePaySlip` handler, fetch the pay slip's `file_url` (already done for the existence check), delete the file from GCS, then delete the DB record
- If the storage deletion fails, the DB record should not be deleted — otherwise the file path is permanently lost with no way to retry cleanup

## Files Affected

| File | Change |
|---|---|
| `internal/storage/storage.go` | Add `DeleteFile` method |
| `internal/handlers/payslip_handlers.go` | Call `DeleteFile` before `DeletePaySlip` in the delete handler |

### PR DESCRIPTION
**Pull request by MohamadNazik**
## Summary
This PR fixes the issue where deleting a pay slip left orphaned files in Firebase Storage. The deletion process now cleans up both the storage object and the database record.

## Changes
- **Storage**: Added functionality to delete files from the storage bucket.
- **Handler**: Updated the delete handler to remove the storage file before the DB record, with graceful handling for files already missing.
- **API Spec**: Updated documentation to reflect file deletion and added missing auth response codes.

Closes #31

### CODE REVIEW

File: pay-slip-app/backend/internal/services/payslip_service.go [hunk 1]
```diff
@@ -41,11 +44,26 @@ func (s *PaySlipService) UpdatePaySlipFile(id, filePath, uploadedBy string) erro
...
+	}
+
+	if err := s.storage.DeleteFile(ctx, ps.FilePath); err != nil {
+		if err != storage.ErrObjectNotExist {
+			return err
+		}
+	}
+
+	return s.DeletePaySlip(ctx, id)
+}
```
Comment (sthanikan2000) [inline pay-slip-app/backend/internal/services/payslip_service.go]: Better to combine as single function `DeletePaySlip`. Do you need both functions separately?
You can also define private helper function if you want, but since the logic is straight forward and simple, using a single function make sense for me.

File: pay-slip-app/backend/cmd/main.go [hunk 2]
```diff
@@ -59,7 +44,7 @@ func main() {
 	// ── HTTP server ───────────────────────────────────────────────────────────
 	mux := http.NewServeMux()
 
-	h := handlers.New(userService, paySlipService, paySlipStorage)
+	h := handlers.New(userService, paySlipService, paySlipService.Storage())
```
Comment (sthanikan2000) [inline pay-slip-app/backend/cmd/main.go]: Your are already having the `paySlipService` parameter then no need to have another parameter `paySlipService.Storage()`

Comment (sthanikan2000) [inline pay-slip-app/backend/cmd/main.go]: And create this handler by defining  `NewPayslipHandler` function. And define the `PayslipHandler` struct as well

**Review by ginaxu1 — APPROVED** [review]

File: pay-slip-app/backend/internal/handlers/handlers.go
Comment (sthanikan2000) [inline pay-slip-app/backend/internal/handlers/handlers.go]: Can you create an issue to remove this file totally, and move the helper functions to `pay-slip-app/backend/internal/utils`?

**Review by sthanikan2000 — APPROVED** [review]
Check these comments, and create new issues for the non existing issues and reply with the issue number, if already issue exists.

PR LGTM to merge.

**Comment by MohamadNazik** [comment]
> @MohamadNazik also squash the commits to 1 or 2 commits

@sthanikan2000 Squashed in to 2 commits.
